name: "Security Analyser"


on:
  pull_request:
    branches: [main]
  push:
    branches: [ "**" ]
  workflow_dispatch:


defaults:
  run:
    shell: bash


jobs:
  # Ref: Relies on your root .gitleaks.toml config. See https://github.com/zricethezav/gitleaks-action
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Using a fetch-depth of '0' clones the entire history. If you want to do a more efficient clone, use '2', but that is not guaranteed to work with pull requests
          fetch-depth: 0
      - name: "Run GitLeaks scan"
        uses: zricethezav/gitleaks-action@v1.3.0
        #uses: crazy-matt/gitleaks-action@master
        with:
          config-path: security/.gitleaks.toml
      - name: "Create Repository Dispatch event for Security Analysis result"
        if: failure()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CI_GH_PAT_REPO_DISPATCH_API_AUTH }}
          event-type: slack-notification
          client-payload: '{"type": "security", "ref": "${{ github.ref }}", "color": "#FF0000", "title": "${{ github.repository }} Leak Analysis", "message": "🚨 Secret(s) exposed"}'
